# This file provides build and function settings for Netlify.

# Build settings for the site.
[build]
  # This line tells Netlify where your serverless functions folder is located.
  # Netlify will automatically look for this directory at the root of your project.
  functions = "netlify/functions"
  
  # Since your index.html is at the root, the publish directory is the root.
  # We can set it to "." to be explicit.
  publish = "."

# Global settings for all functions.
[functions]
  # Sets the maximum execution time for a function in seconds.
  # The maximum for Netlify's free tier is 10 seconds.
  timeout = 10
