# File: netlify.toml

# Build settings
[build]
  # This tells Netlify where your website's main files are.
  # Since index.html is at the root, we can set this to "."
  publish = "."
  # This tells Netlify where to find your serverless functions.
  functions = "netlify/functions"

# Settings for your serverless functions
[functions]
  # This sets the timeout for your functions. On the free tier,
  # the maximum is 10 seconds, but it's good practice to set it explicitly.
  # If you upgrade your Netlify plan, you can increase this number.
  timeout = 10